name: Check code style and tests
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    steps:
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          php-version: '7.0'
          path: $HOME/.composer/cache
          key: '${{ runner.os }}-${{ hashFiles(''TODO'') }}'
      - uses: actions/checkout@v2
      - run:  composer self-update
      - run:  composer install --prefer-dist --no-interaction
      - run: export XDEBUG_MODE=coverage
      - run: vendor/bin/phpcs
      - run: vendor/bin/phpunit
