name: Check code style and tests
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    steps:
      - name: Setup PHP with Xdebug 2.x
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: xdebug2
      - run:  composer self-update
      - run:  composer install --prefer-dist --no-interaction
      - run: export XDEBUG_MODE=coverage
      - run: vendor/bin/phpcs
      - run: vendor/bin/phpunit
