name: Check code style and tests
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkouut
      uses: actions/checkout@v2
    
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: 7.0
        version: 2
        
    - name: Run phpcs
      run: vendor/bin/phpcs
      
    - name: Run phpunit
      run: vendor/bin/phpunit
      
